config/routes.rb
Rails.application.routes.draw do

  root 'meetings#index'

  resources :meetings do
    member do
      post 'finish'
      post 'manage_participant'
      delete 'manage_participant'
    end
    collection do
      get 'dashboard'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/meeting.rb
class Meeting < ApplicationRecord

  has_many :participations
  has_many :participants, :through => :participations
  has_many :active_participants, -> {Participation.active}, through: :participations, :source => :participant
  #FIXME make this test
  scope :current_month, lambda { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }
  scope :today, lambda { where(created_at: Time.now.beginning_of_day..Time.now.end_of_day) }

  def add_participant
    self.participants << Participant.new
  end

  def remove_participant
    participation = self.participations.active.first
    participation.update!(present: false) unless participation.nil?
  end

  scope :duration, lambda { sum(:duration) }


  #FIXME make this test
  def duration
    ((self.finish || Time.now) - self.created_at).to_i
  end

  #FIXME make this test
  def self.time_for_humans(time)
    return0 if time.nil?
    d = time
    d = d.sum if d.is_a?(Array)
    "#{d.in_hours.to_i.to_s.rjust(2, '0')}:#{d.in_minutes.to_i.to_s.rjust(2, '0')}:#{d.in_seconds.to_i.to_s.rjust(2, '0')}"
  end

  #FIXME make this test
  def spent_time_by_participant
    self.participations.map do |participation|
      (participation.updated_at - participation.created_at).to_i
    end
  end

  #FIXME make this test
  def all_time_spent_by_participants
    self.spent_time_by_participant.sum
  end

  #FIXME make this test
  def cost
    (self.all_time_spent_by_participants.to_f/60/60) * self.hour_cost
  end

  # FIXME make this test
  def close!
    Meeting.transaction do
      now = DateTime.now.in_time_zone
      self.finish = now
      self.participations.active.update_all(:present => false, :updated_at => now)
      self.save!
    end
  end

  protected

  def hour_cost
    100
  end

end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :participations
  has_many :meetings, :through => :participations
end

app/models/participation.rb
class Participation < ApplicationRecord
  scope :active, lambda { where(:present => true) }
  #FIXME make this test
  scope :current_month, lambda { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }
  scope :today, lambda { where(created_at: Time.now.beginning_of_day..Time.now.end_of_day) }
 

  self.table_name = "meetings_participants"

  belongs_to :participant
  belongs_to :meeting

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :finish, :manage_participant]

  def index
    @meetings = Meeting.page(params[:page])
  end

  def show
  end

  def new
    meeting = Meeting.new
    meeting.participants << Participant.new
    meeting.save!
    redirect_to edit_meeting_path(meeting)
  end

  # GET /meetings/1/edit
  def edit
  end

  def manage_participant
    @meeting.add_participant if request.post?
    @meeting.remove_participant if request.delete?
  end

  def finish
    @meeting.close!
    redirect_to meeting_path(@meeting)
  end

  def dashboard
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def button(content, options = {})
    color = options[:color] || 'primary'
    content_tag(:button, content, :type => 'button', :class => "btn btn-#{color} btn-lg")
  end

  def plus_button
    content_tag(
      :button, 
      content_tag(:i, '' , :class => 'fa fa-plus'), 
      :type => 'button', :class => 'btn btn-success btn-circle btn-xl'
    )
  end

  def minus_button
    content_tag(
      :button, 
      content_tag(:i, '' , :class => 'fa fa-minus'), 
      :type => 'button', :class => 'btn btn-danger btn-circle btn-xl'
    )
  end

  def panel_information(title,amount,options = {})
    color = options[:color] || 'green'
    icon = options[:icon] || 'fa-tasks'
    content_tag(:div,
      content_tag(:div,
        content_tag(:div, 
          content_tag(:div,
            content_tag(:div, 
              content_tag(:i, '', :class => "fa #{icon} fa-5x"),
              :class => 'col-xs-3'
            ) +
            content_tag(:div, 
              content_tag(:div, amount, :class => "huge"),
              :class => 'col-xs-9 text-right'
            ),
            :class => 'row'
          )
        ),
        :class => 'panel-heading'
      ) +
      content_tag(:div, 
        content_tag(:span, title, :class => 'detail'),
        :class => 'panel-footer'
      ),
      :class => "panel panel-#{color}"
    )

  end  


end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(:meeting_meter) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="actions">
    <% if params[:action]=="new" %>
      <%= f.submit 'Iniciar reunião' %>
    <% else %>
      <%= f.submit 'Encerrar reunião', :onclick => "document.getElementById('end_meeting').value='true';" %>
    <% end %>
  </div>
<% end %>

app/views/meetings/dashboard.html.erb
<div id='dashboard'>
  <h1>
    <%= t(:meeting_meter) %>
    <span> <%= link_to t(:dashboard_link, link: root_url), root_url %> </span>
  </h1>
  <div class='info'>
<%= t(
       :dashboard_info, 
       :participation_month_count => Participation.current_month.count, 
       :meeting_month_amount => Meeting.current_month.count,
       :meeting_duration => time_ago_in_words(Meeting.current_month.map{|m| m.duration}.sum.seconds.from_now),
       :average_meeting_duration => time_ago_in_words((Meeting.current_month.map{|m| m.duration}.sum/Meeting.current_month.count).seconds.from_now),
       :participants_month_duration => time_ago_in_words(Meeting.current_month.map{|p| p.all_time_spent_by_participants}.sum.seconds.from_now),
       :average_participants_month_duration => time_ago_in_words((Meeting.current_month.map{|p| p.all_time_spent_by_participants}.sum/Participation.current_month.count).seconds.from_now)
     ).html_safe %>
  </div>
</div>

<script>
function update() { location.reload();}

$(document).ready(function($){
  window.setInterval('update()', 2*1000);
});

</script>

app/views/meetings/edit.html.erb
<h1><%= t(:meeting_meter) %></h1>

<div class="time_duration" id='time'>
</div>      

<div class='participants'>
  <h2> <%= t(:participants_title) %> </h2>
  <p class='amount' id='participants_amount'>  <%= @meeting.active_participants.count %></p>
</div>
<div class='actions'>
  <%= link_to plus_button, manage_participant_meeting_path(@meeting), remote: true, method: :post %>
  <%= link_to minus_button, manage_participant_meeting_path(@meeting), remote: true, method: :delete %>
</div>

<%= link_to button(t(:finish_meeting)), finish_meeting_path(@meeting), :method => :post %>

<script>
 show();
 startAt(<%= TimeDifference.between(@meeting.created_at, Time.zone.now).in_seconds.to_i * 1000 %>);
</script>

app/views/meetings/index.html.erb
<h1 class='big center'><%= t(:meeting_meter) %></h1>

<div id='start-page' >
    <%= link_to button(t(:meeting_statistics), :color => 'success'), dashboard_meetings_path %>
    <%= link_to button(t(:start_meeting)), new_meeting_path %>
</div>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<h1><%= t(:meeting_meter) %></h1>
<h2><%= t(:meeting_statistics) %></h2>
<div class='col-lg-3 col-md-6'>
  <%= panel_information(t(:meeting_time), time_ago_in_words(@meeting.duration.seconds.from_now), {:color => 'primary', :icon => 'fa-clock-o'}) %>
</div>
<div class='col-lg-3 col-md-6'>
  <%= panel_information(t(:stakeholders), @meeting.participants.count, {:color => 'yellow', :icon => 'fa-group'}) %>
</div>
<div class='col-lg-3 col-md-6'>
  <%= panel_information(t(:estimated_total_cost), number_to_currency(@meeting.cost), {:icon => 'fa-money'}) %>
</div>

<div class='col-lg-3 col-md-6'>
  <%= panel_information(t(:spent_total_time), time_ago_in_words(@meeting.all_time_spent_by_participants.seconds.from_now), {:color => 'red', :icon => 'fa-signal'}) %>
</div>

<%= link_to button(t(:understood)), meetings_path %>